digitalocean:
  group:
  - name: control-plane
    node:
    - maglev-cp-alpha
    - maglev-cp-beta
    - maglev-cp-gamma
  - name: worker
    node:
    - maglev-worker-alpha
    - maglev-worker-beta
    - maglev-worker-gamma
    - maglev-worker-delta
    - maglev-worker-epsilon
  generics:
  - name: default
    config:
    - script: |-
        #!/bin/bash
        set -e

        apt-get update
        curl -fsSL https://github.com/rodolfovillaruz/cisak/releases/download/v0.1.12/cisak-v0.1.11-linux-amd64.tar.gz | tar -xz
        install -m 755 -o root -g root cisak /usr/local/bin/cisak
        cisak generate
        cisak install -y
      ssh-public-key: ~/.ssh/id_ed25519.pub
      user: root
      control-plane-endpoint: k8s-api.example.com
  specs:
  - name: control-plane
    config:
    - machine-type: s-2vcpu-4gb
      boot-disk-image: ubuntu-24-04-x64
      boot-disk-size: 20
      ip-address: public
  - name: worker
    config:
    - machine-type: s-2vcpu-4gb
      boot-disk-image: ubuntu-24-04-x64
      boot-disk-size: 50
  rules:
  - group: control-plane
    generics: default
    specs: control-plane
  - group: worker
    generics: default
    specs: worker
  credentials:
    token: "your-digitalocean-api-token"
    region: nyc1