gcp:
  provisioner:
    type: public
    node: maglev-cp-alpha
  group:
  - name: public
    type: control-plane
    node:
    - maglev-cp-alpha
  - name: private
    type: control-plane
    node:
    - maglev-cp-beta
    - maglev-cp-gamma
  - name: worker-nodes
    type: worker
    node:
    - maglev-worker-alpha
    - maglev-worker-beta
    - maglev-worker-gamma
    - maglev-worker-delta
    - maglev-worker-epsilon
  specs:
  - name: cisak
    config:
    - script: |-
        #!/bin/bash
        set -e

        apt-get update
        curl -fsSL https://github.com/rodolfovillaruz/cisak/releases/download/v0.1.12/cisak-v0.1.12-linux-amd64.tar.gz | tar -xz
        install -m 755 -o root -g root cisak /usr/local/bin/cisak
        cisak generate
        cisak install -y
      ssh-public-key: ~/.ssh/id_ed25519.pub
      user: ubuntu
      machine-type: e2-standard-2
      boot-disk-image: ubuntu-2404-lts-amd64
      control-plane-endpoint: k8s-api.example.com
  - name: control-plane-public
    config:
    - boot-disk-size: 20
      ip-address: public
  - name: control-plane-private
    config:
    - boot-disk-size: 20
  - name: worker-nodes
    config:
    - boot-disk-size: 50
  rules:
  - group:
    - public
    specs:
    - cisak
    - control-plane-public
  - group:
    - private
    specs:
    - cisak
    - control-plane-private
  - group: worker-nodes
    specs:
    - cisak
    - worker-nodes
  credentials:
    client-email: my-service-account@my-project.iam.gserviceaccount.com
    private-key: "path/to/private-key.pem"
    project-id: my-project
    zone: us-central1-a